version: '2.2'

services:
    dm-default:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: generator
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ./src:/workspace/src
            - /etc/localtime:/etc/localtime

    dm-linux:
        extends:
            service: dm-default
        network_mode: host
