version: '2.2'

services:
    dm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: generator
        network_mode: host
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ./src:/workspace/src
            - /etc/localtime:/etc/localtime
